### ISSUE TITLE
Error when starting up on Ubuntu 22.04

### ISSUE THREAD

**Issue by xpara97** [deaFPS/cs2-kz-lua#1]
OS: Ubuntu 22.04
Script Runtime Error: /AMP/counter-strike2/730/game/csgo/scripts/vscripts/kz.lua:56: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
[C]: in function 'ipairs'
/AMP/counter-strike2/730/game/csgo/scripts/vscripts/kz.lua:56: in function </AMP/counter-strike2/730/game/csgo/scripts/vscripts/kz.lua:53>

**Comment by deaFPS** [comment]
fixed
